### PR TITLE
feat: Added a new way to redefine how we declare EdgeInsets

### LINKED ISSUE #260: feat: A new way to redefine how we declare`EdgeInsets`.
**Description**

Right now there is only one way to define MiraiEdgeInsets.

```
              "padding": {
                "top": 8,
                "left": 12,
                "right": 12,
                "bottom": 8
              }
```

There should be a better to define it like.

1. For giving same padding to all.

```
"padding`: 8,
```

2. Define padding for all dir.

```
"padding": [8, 12, 12, 8]
```

This way it will be easier to define padding and make the JSON smaller.

### PR DESCRIPTION
**Pull request by superiorsd10**
## Description

Previously, there was only one way to define `MiraiEdgeInsets` and it looked like this

```
              "padding": {
                "top": 8,
                "left": 12,
                "right": 12,
                "bottom": 8
              }
```

In this pull request, I have added the two new ways as suggested to declare `MiraiEdgeInsets`. 

1. To give the same padding to all directions, you can now just write like this. 

```
              "padding": 10, 
```

2. To give padding to all directions, but in a better and more concise way, you can now just write it like this. 

```
              "padding": [10, 12, 12, 10]
```

To approach this issue, I have defined a new static method inside `MiraiEdgeInsets` named `_fromJson` that takes a `dynamic` argument and checks if the type of argument is among three acceptable types i.e. `num, List<num>, Map<String, dynamic>`, and returns `MiraiEdgeInsets`; otherwise, throw an `ArgumentError`. 

## Related Issues

Closes #260 

## Screen Recording

https://github.com/Securrency-OSS/mirai/assets/92971894/6396a9b4-71fd-4272-a5ce-28cb173999e3

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

### CODE REVIEW

**Comment by superiorsd10** [comment]
Hello @divyanshub024 👋

On replicating the behavior stated by you, it's working fine, and I'm not getting any errors. Can you please tell me more about the issue?

**Comment by divyanshub024** [comment]
Hey @superiorsd10, 

I took the pull again and it still showed the same error.

https://github.com/Securrency-OSS/mirai/assets/16731434/a301932d-3160-4f61-8822-43be6dfa7db7

**Comment by superiorsd10** [comment]
Hello @divyanshub024 👋

I have fixed the above issue. You can pull the latest changes now, and check if it works. I have tested it on my end, and it's working fine. 

Thank you,

**Review by divyanshub024 — APPROVED** [review]
LGTM!!
Thank you @superiorsd10 🎉

**Pull request merged**
