### PR TITLE
Securrency-OSS/mirai#191 - :rocket: Added support for align widget

### LINKED ISSUE #191: feat: Add align widget

### PR DESCRIPTION
**Pull request by loud-at-heart**
## Description

To add align support for Mirai

## Related Issues

Closes #191 

## Type of Change

Added parser for Align widget

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by divyanshub024** [comment]
@loud-at-heart Thank you for the PR. 🚀  
Can you please add the align widget example in Mirai Gallery? And please the PR checks, it's failing. 
```
[mirai]:    info - lib/src/framework/mirai.dart:11:8 - The import of 'package:mirai/src/parsers/mirai_align/mirai_align.dart' is unnecessary because all of the used elements are also provided by the import of 'package:mirai/src/parsers/parsers.dart'. Try removing the import directive. - unnecessary_import
```

**Comment by loud-at-heart** [comment]
> @loud-at-heart Thank you for the PR. 🚀 Can you please add the align widget example in Mirai Gallery? And please the PR checks, it's failing.
> 
> ```
> [mirai]:    info - lib/src/framework/mirai.dart:11:8 - The import of 'package:mirai/src/parsers/mirai_align/mirai_align.dart' is unnecessary because all of the used elements are also provided by the import of 'package:mirai/src/parsers/parsers.dart'. Try removing the import directive. - unnecessary_import
> ```

Do you need a seperate tile or adding it on container will work

**Comment by divyanshub024** [comment]
@loud-at-heart This looks good!!

**Comment by loud-at-heart** [comment]
> @loud-at-heart This looks good!!

I added a separate tile too for align..

**Comment by divyanshub024** [comment]
@loud-at-heart I think you forgot to export the `MiraiAlign` in `parsers.dart`

**Comment by loud-at-heart** [comment]
> MiraiAlign

Sure making the change

**Review by divyanshub024 — APPROVED** [review]

**Comment by divyanshub024** [comment]
Thank you for this PR @loud-at-heart 
We are grateful for your contribution 🤩

**Pull request merged**
